FROM rust:1.78.0-alpine as builder

RUN apk add --no-cache build-base musl-dev openssl-dev openssl

WORKDIR /app

COPY ./server/Cargo.toml ./Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo fetch
RUN cargo build
RUN rm src/main.rs

COPY ./server/src ./src/
RUN touch src/main.rs
RUN cargo build

FROM alpine as runner
WORKDIR /app
COPY --from=builder /app/target/debug/server app

CMD ["./app"]